package com.rht.rht2.web.base;

import javax.inject.Inject;

import com.rht.rht2.logic.impl.AccountStatusContainer;
import com.rht.rht2.logic.impl.TestService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalSplitPanel;

public class Base extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	private Table table_1;

	@Inject
	TestService testService;

	@Inject
	AccountStatusContainer accountStatusContainer = new AccountStatusContainer();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Base() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		createTable();
		bind();
	}

	private void createTable() {
		// table_1
		table_1 = new Table("Account Status");
		table_1.setWidth("483px");
		table_1.setHeight("-1px");
		verticalSplitPanel_1.addComponent(table_1);

	}

	private void bind() {

		// Bind it to a container

		table_1.setContainerDataSource(accountStatusContainer);
		table_1.setVisibleColumns(new String[] { "accountStatusId", "status" });
		table_1.setImmediate(false);

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		mainLayout
				.addComponent(verticalSplitPanel_1, "top:20.0px;left:20.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("780px");
		verticalSplitPanel_1.setHeight("440px");

		return verticalSplitPanel_1;
	}

}
